HBSD: compile fix
Traceback (most recent call last):
  File "/usr/ports/www/firefox-esr/work/firefox-78.9.0/configure.py", line 181, in <module>
    sys.exit(main(sys.argv))
  File "/usr/ports/www/firefox-esr/work/firefox-78.9.0/configure.py", line 52, in main
    sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
  File "/usr/ports/www/firefox-esr/work/firefox-78.9.0/python/mozbuild/mozbuild/configure/__init__.py", line 494, in run
    raise InvalidOptionError(msg)
mozbuild.configure.options.InvalidOptionError: Unknown option: --enable-pie

(cherry picked from commit 6f608a5e1badac2b748a9575eef11fc2d35e8099)
Signed-off-by: Shawn Webb <shawn.webb@hardenedbsd.org>